version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/idealog
      - SECRET_KEY=devnotcompletelyrandomsecretkey
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/idealog
      - REDISCLOUD_URL=redis://localhost
      - SECRET_KEY=devnotcompletelyrandomsecretkey
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - CELERY_TASK_IGNORE_RESULT=true
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  redis:
    image: redis
    ports:
      - "6379:6379"
