version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/idealog
      - SECRET_KEY=devnotcompletelyrandomsecretkey
      - REDISCLOUD_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_IGNORE_RESULT=true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    depends_on:
      - worker
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/idealog
      - REDISCLOUD_URL=redis://redis:6379/0
      - SECRET_KEY=devnotcompletelyrandomsecretkey
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_IGNORE_RESULT=true
    depends_on:
      - redis
      - db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: idealog
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  db-data: